/**
 * Universal Test Engine — Global Teardown
 *
 * Runs once after the entire test suite completes.
 * Generates a lightweight summary JSON.
 */

import { FullConfig } from '@playwright/test';
import { getEnvName } from '../config/env.config';
import { writeSummary } from '../src/utils/report-helper';
import * as fs from 'fs';
import * as path from 'path';

async function globalTeardown(config: FullConfig): Promise<void> {
  // Try to read the JSON results generated by the json reporter
  const resultsPath = path.resolve('reports', 'results.json');
  if (fs.existsSync(resultsPath)) {
    try {
      const results = JSON.parse(fs.readFileSync(resultsPath, 'utf-8'));
      const suites = results.suites ?? [];

      let total = 0;
      let passed = 0;
      let failed = 0;
      let skipped = 0;

      function countSpecs(suite: any) {
        for (const spec of suite.specs ?? []) {
          for (const test of spec.tests ?? []) {
            total++;
            const status = test.results?.[0]?.status;
            if (status === 'passed') passed++;
            else if (status === 'failed' || status === 'timedOut') failed++;
            else if (status === 'skipped') skipped++;
          }
        }
        for (const child of suite.suites ?? []) {
          countSpecs(child);
        }
      }
      suites.forEach(countSpecs);

      writeSummary('reports', {
        environment: getEnvName(),
        totalTests: total,
        passed,
        failed,
        skipped,
        duration: results.stats?.duration ?? 0,
        timestamp: new Date().toISOString(),
      });

      console.log('\n📊 Test Summary:');
      console.log(`   Total: ${total} | ✅ Passed: ${passed} | ❌ Failed: ${failed} | ⏭ Skipped: ${skipped}`);
    } catch {
      // results file not available or malformed — skip summary
    }
  }
}

export default globalTeardown;
